In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
data = pd.read_csv(r"C:\Users\Acer\Downloads\titanic.csv")

data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

1. Import Libraries
2. Read data
3. view first 5 and analyze it
4. check for null values and proceed accordingly
5. Fill the null values or drop accordingly
6. check for datatypes
7. convert object to numerical
8. split features and target
9. train model
10. Evaluate model

In [3]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

AS the cabin has missing values of around 687 that is about 77% of the dataset, filling it also create a artificial bias of the dataset, hence dropping it

In [4]:
data = data.drop(columns=['Cabin'])

In [5]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

filling the age null values with median values , as the age is continuous and may have outliers , so using median instead of mean

In [6]:
data['Age'] = data['Age'].fillna(data['Age'].median())

In [7]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

filling the embarked null values with mode, as it is a categorical column filling with the most frequent one

In [8]:
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [9]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [11]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [12]:
data['Sex'] = data['Sex'].replace({'male':0,"female":1})

In [13]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(6), object(3)
memory usage: 76.7+ KB

droping the name, ticket, passengerId as they are of no use in model learning

In [15]:
data.drop(columns=['Name','PassengerId','Ticket'], axis=1, inplace=True)

In [16]:
data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    0  22.0      1      0   7.2500        S
1         1       1    1  38.0      1      0  71.2833        C
2         1       3    1  26.0      0      0   7.9250        S
3         1       1    1  35.0      1      0  53.1000        S
4         0       3    0  35.0      0      0   8.0500        S

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(5), object(1)
memory usage: 55.8+ KB

In [18]:
data.nunique()

Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Embarked      3
dtype: int64

In [19]:
data = pd.get_dummies(data, columns=['Embarked'], drop_first=True)

In [20]:
data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    0  22.0      1      0   7.2500           0           1
1         1       1    1  38.0      1      0  71.2833           0           0
2         1       3    1  26.0      0      0   7.9250           0           1
3         1       1    1  35.0      1      0  53.1000           0           1
4         0       3    0  35.0      0      0   8.0500           0           1

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    int64
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_Q  891 non-null    uint8
 8   Embarked_S  891 non-null    uint8
dtypes: float64(2), int64(5), uint8(2)
memory usage: 50.6 KB

In [22]:
x = data.drop(columns=['Survived'], axis=1)
y = data['Survived']

In [23]:
print(x)
print(y)

     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         3    0  22.0      1      0   7.2500           0           1
1         1    1  38.0      1      0  71.2833           0           0
2         3    1  26.0      0      0   7.9250           0           1
3         1    1  35.0      1      0  53.1000           0           1
4         3    0  35.0      0      0   8.0500           0           1
..      ...  ...   ...    ...    ...      ...         ...         ...
886       2    0  27.0      0      0  13.0000           0           1
887       1    1  19.0      0      0  30.0000           0           1
888       3    1  28.0      1      2  23.4500           0           1
889       1    0  26.0      0      0  30.0000           0           0
890       3    0  32.0      0      0   7.7500           1           0

[891 rows x 8 columns]
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [25]:
DT = DecisionTreeClassifier(max_depth=3)
DT.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [27]:
y_pred = DT.predict(x_test)

In [28]:
print(accuracy_score(y_test, y_pred))

0.8212290502793296

In [29]:
print(confusion_matrix(y_test,y_pred))

[[100  17]
 [ 15  47]]

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86       117
           1       0.73      0.76      0.75        62

    accuracy                           0.82       179
   macro avg       0.80      0.81      0.80       179
weighted avg       0.82      0.82      0.82       179

The model achieves an overall accuracy of ~82%, with strong performance on class 0 and slightly lower performance on class 1. While errors are relatively balanced, the model shows mild bias toward the majority class. The recall for class 1 (76%) indicates that some positive cases are still being missed. Overall, the model performs reasonably well but could be improved for better detection of class 1 instances.

In [31]:
import joblib

joblib.dump(DT,'titanic.pkl')

['titanic.pkl']

In [32]:
loaded_model = joblib.load('titanic.pkl')

In [33]:
new_passenger = [[
    3,      # Pclass
    0,      # Sex
    22,     # Age
    1,      # SibSp
    0,      # Parch
    7.25,   # Fare
    False,  # Embarked_Q
    True    # Embarked_S
]]

In [34]:
prediction = loaded_model.predict(new_passenger)

c:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [35]:
prediction

array([0], dtype=int64)

In [36]:
new_data = pd.DataFrame({
    'Pclass':[1],
    'Sex':[1],
    'Age':[30],
    'SibSp':[1],
    'Parch':[0],
    'Fare':[100],
    'Embarked_Q':[False],
    'Embarked_S':[False]
})

prediction = loaded_model.predict(new_data)

print(prediction)

[1]